spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Keanyuan/spring-cloud-config-repo.git
          username: keanyuan
          password: as9787105
          basedir: /Users/kean/MavenBuild/config-repo


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "*"