eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#spring.cloud.stream.defaultBinder=boss
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
  cloud:
    stream:
      rabbit:
        bindings:
          myMessageInput:
            group: order
            content-type: application/json
server:
  port: 8082

#PRODUCT:
#    ribbon:
#      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule