spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
# url 前缀
server:
  servlet:
    context-path: /sell

#logging:
#  pattern:
#    设置logger格式
#    console: "%d - %msg%n"
#  path: /Users/kean_qi/Logger/sell/
#  file: /Users/kean_qi/Logger/sell/sell.log
#  level:
#    com.anjiplus.sell.LoggerTest: debug