spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://192.168.0.105:3306/sell?characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://192.168.215.28:3306/sell?characterEncoding=utf-8&useSSL=false
    username: root
#    password: root
    password: 123456
  jpa:
    show-sql: true
  jackson:
#    default-property-inclusion: non_null
# url 前缀
server:
  servlet:
    context-path: /sell

#logging:
#  pattern:
#    设置logger格式
#    console: "%d - %msg%n"
#  path: /Users/kean_qi/Logger/sell/
#  file: /Users/kean_qi/Logger/sell/sell.log
#  level:
#    com.anjiplus.sell.LoggerTest: debug
wechat:
  mpAppId: wx0fd8a86920ade6d1
  mpAppSecret: 9cf8d968fc72c72b720c7e66fb1d53d3
  openAppId: wx0fd8a86920ade6d1
  openAppSecret: 9cf8d968fc72c72b720c7e66fb1d53d3
  mchId: wx0fd8a86920ade6d1
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://keansell.natapp1.cc/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projecturl:
  wechatMpAuthorize: http://keansell.natapp1.cc
  wechatOpenAuthorize: http://keansell.natapp1.cc
  sell: http://keansell.natapp1.cc