spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gjp?characterEncoding=utf8&useSSL=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true